### ISSUE TITLE
Provide the ability to replace file source code that matched AST node

### ISSUE THREAD

**Issue by emosheeep** [unplugin/unplugin-ast#33]
### Clear and concise description of the problem

Thanks for your efforts on it first! I've encountered a situation that I want to change the source code, but for now all of my modifications are limited in the range of AST node.

For example, I want to manually realize the dynamic import logic, I got the import paths by AST analysis and transformed corresponding import expression into my own function `__varDynamicImport__`, and then I need to inject this function at the top or bottom of the source code, but I can't manage to it.

Have this ability realized yet? If not, may be this plugin could provide a API to realize it, I think of it useful!

### Suggested solution

Not too many suggestions. 😅

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
Implemented `finalize` hook in `v0.10.0`.
