### ISSUE TITLE
`@babel/generator`default import bug

### ISSUE THREAD

**Issue by Groupguanfang** [unplugin/unplugin-ast#82]
### Describe the bug

I try to use this plugin in rollup like this:
```typescript
ast.rollup({
    transformer: [
      {
        transform(node) {
          return node;
        },
      },
    ],
  })
```
I don't change anything, but it throw an `TypeError`:
```sh
[!] (plugin unplugin-ast) TypeError: generate is not a function
src/index.ts
    at transform (/node_modules/.pnpm/unplugin-ast@0.8.2_rollup@4.13.0/node_modules/unplugin-ast/dist/chunk-GG4PBWTU.js:95:29)
    at transform (/node_modules/.pnpm/rollup@4.13.0/node_modules/rollup/dist/shared/rollup.js:19542:16)
    at ModuleLoader.addModuleSource (/node_modules/.pnpm/rollup@4.13.0/node_modules/rollup/dist/shared/rollup.js:19758:36)
```

I search the google and find this discussion: [TypeError: generate is not a function](https://github.com/babel/babel/discussions/14815)

Then I directly to change `node_modules` in `/node_modules/.pnpm/unplugin-ast@0.8.2_rollup@4.13.0/node_modules/unplugin-ast/dist/chunk-GG4PBWTU.js:95:29`
```typescript
const generated = generate(result);
```
to this:
```typescript
const generated = generate.default(result);
```
It works.

Can fix this little bug?

### Reproduction

https://github.com/Groupguanfang/unplugin-ast-babel-generator-default-import

### System Info

```Shell
- System:
  - OS: macOS 14.3.1
  - CPU: (8) arm64 Apple M1
  - Memory: 114.63 MB / 16.00 GB
  - Shell: 5.9 - /bin/zsh
- Binaries:
  - Node: 18.19.1 - ~/.nvmd/versions/18.19.1/bin/node
  - Yarn: 1.22.19 - ~/.nvm/versions/node/v20.6.1/bin/yarn
  - npm: 10.2.4 - ~/.nvmd/versions/18.19.1/bin/npm
  - pnpm: 8.8.0 - ~/.nvm/versions/node/v20.6.1/bin/pnpm
  - bun: 1.0.2 - ~/.bun/bin/bun
- Browsers:
  - Chrome: 120.0.6099.216
  - Edge: 122.0.2365.63
  - Safari: 17.3.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Fixed & released as `unplugin-ast@0.9.0`
